// Code generated by goplus from deps.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package development wires every brick into one place for IDE and REPL
// use. It is generated by goforge; do not edit by hand.
package development

import (
	_ "goforge.dev/cupel/bases/cli"
	_ "goforge.dev/cupel/components/architecture"
	_ "goforge.dev/cupel/components/claude"
	_ "goforge.dev/cupel/components/claudecode"
	_ "goforge.dev/cupel/components/gen"
	_ "goforge.dev/cupel/components/prompt"
	_ "goforge.dev/cupel/components/spec"
)
