// Code generated by goplus from core.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package internal holds the prompt component implementation.
package internal

import (
	"fmt"
	"strings"
)

// SpecView is the projection of a spec.Spec the templates need, kept here so the
// internal package does not import the spec interface (avoiding an import cycle
// through the brick boundary).
type SpecView struct {
	Name        string
	Interface   string
	TestPackage string
	Text        string
}

// System is the model's standing instructions. Stable across calls so it can be
// prompt-cached.
const System = `You are a Go testing expert generating tests from an English specification.

You write tests in three distinct, clearly separated styles for the same specification:

1. EXAMPLE TESTS — concrete, readable cases. One behaviour per test function, named TestXxx, using table-free straight-line assertions. Where the API has documentable output, also include a Go testable Example function (func ExampleXxx) with an "// Output:" comment.

2. PARAMETERIZED / DATA-DRIVEN TESTS — table-driven tests: a slice of named struct cases iterated with t.Run(tc.name, ...). Cover boundaries, equivalence classes, and error cases drawn from the specification.

3. PROPERTY-BASED TESTS — invariants that must hold for all inputs, checked with the standard library "testing/quick" (quick.Check / quick.CheckEqual). State each property as a comment, then assert it. Do not invent third-party property libraries.

Hard requirements:
- Output ONE self-contained Go test file and NOTHING else. No prose, no explanation.
- Standard library only. Allowed imports: testing, testing/quick, and other std packages. No third-party modules.
- The file MUST be gofmt-clean and compile.
- Group the file into three commented sections in the order above.
- Tests should reference the component's exported API by the names implied by the specification; if an exact symbol is unknown, choose the most idiomatic Go name and add a short comment noting the assumption.`

// User renders the per-spec user message.
func User(v SpecView) string {
	var b strings.Builder
	fmt.Fprintf(&b, "Generate the Go test file for the %q component.\n\n", v.Name)
	fmt.Fprintf(&b, "The file MUST declare exactly: package %s\n", v.TestPackage)
	fmt.Fprintf(&b, "It tests the public package %q (import path ends in components/%s).\n\n", v.Interface, v.Name)
	b.WriteString("Specification:\n")
	b.WriteString(quote(v.Text))
	b.WriteString("\n\nReturn only the Go source for the test file, optionally inside a single ```go fenced block.")
	return b.String()
}

// quote indents the spec text as a block so it is unambiguous in the prompt.
func quote(s string) string {
	lines := strings.Split(s, "\n")
	for i, ln := range lines {
		lines[i] = "  " + ln
	}
	return strings.Join(lines, "\n")
}
